"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
from api.docs.tags import API_TAGS

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Authentication settings
AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]
MAX_LOGIN_ATTEMPTS = 5  # Lock account after 5 failed attempts
LOGIN_LOCKOUT_DURATION = 3600

# Session settings
SESSION_COOKIE_AGE = 3600
SESSION_COOKIE_AGE_REMEMBER = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'None' if DEBUG else 'Lax'
CSRF_COOKIE_SAMESITE = 'None' if DEBUG else 'Lax'
CSRF_COOKIE_SECURE = True


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Security settings
PASSWORD_EXPIRATION_DAYS = 90

# Default role
# DEFAULT_USER_ROLE = 'basic_user'

# MFA settings
MFA_TOKEN_EXPIRY = 300  # 5 minutes

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detailed': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
        'ml_console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'detailed',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': 'logs/security.log',
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'detailed',
        },
    },
    'loggers': {
        'applications.views': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'applications.signals': {
            'handlers': ['ml_console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'ml_model': {
            'handlers': ['ml_console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'src.credit_scorer': {
            'handlers': ['ml_console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'your_app_name.views': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}



# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Risk model paths
RISK_MODEL_PATH = os.path.join(BASE_DIR, 'ai_models/risk_model_v1.pkl')
SCALER_PATH = os.path.join(BASE_DIR, 'ai_models/scaler_v1.pkl')
DECISION_MODEL_PATH = os.path.join(BASE_DIR, 'ai_models/decision_model_v1.pkl')

# Risk model features
RISK_MODEL_FEATURES = [
    'age', 'marital_status', 'employment_duration', 
    'monthly_income', 'net_worth', 'credit_score',
    'requested_amount', 'loan_term'
]

# Decision policy rules
DECISION_POLICY_RULES = {
    'max_approval_amount': 50000,
    'base_interest_rate': 5.0,
    'min_risk_score_for_approval': 500,
    'max_debt_to_income': 0.45
}

# Behavioral thresholds
BEHAVIORAL_THRESHOLDS = {
    'alert_threshold': 0.3,
    'update_threshold': 0.7,
    'typing_weight': 0.7,
    'mouse_weight': 0.3
}

BEHAVIORAL_ANALYSIS_ENABLED = False

if DEBUG:
    BEHAVIORAL_MODELS = {
        'TYPING_MODEL_PATH': '/dev/null',
        'MOUSE_MODEL_PATH': '/dev/null',
        'BEHAVIORAL_THRESHOLD': 0.7
    }
else:
    BEHAVIORAL_MODELS = {
        'TYPING_MODEL_PATH': os.path.join(BASE_DIR, 'ai_models/typing_model.pkl'),
        'MOUSE_MODEL_PATH': os.path.join(BASE_DIR, 'ai_models/mouse_model.pkl'),
        'BEHAVIORAL_THRESHOLD': 0.7
    }


# Document verification
ADVANCED_DOCUMENT_VERIFICATION = True
DOCUMENT_VERIFICATION_API_KEY = os.getenv('DOCUMENT_VERIFICATION_API_KEY')
DOCUMENT_TEMPLATES = {
    'DRIVER_LICENSE': {
        'dimensions': (3.375, 2.125),
        'security_features': ['hologram', 'microprint']
    },
    'PASSPORT': {
        'dimensions': (5.0, 3.5),
        'security_features': ['mrz', 'watermark']
    }
}


# Email settings for password reset
if DEBUG:
    # For development - print emails to console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # For production - use SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST')
    EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', True)
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@creditrisk.com')
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', 'support@creditrisk.com')

# AWS SES Configuration for OTP emails
AWS_SES_ACCESS_KEY_ID = os.getenv('AWS_SES_ACCESS_KEY_ID')
AWS_SES_SECRET_ACCESS_KEY = os.getenv('AWS_SES_SECRET_ACCESS_KEY')
AWS_SES_REGION = os.getenv('AWS_SES_REGION', 'us-east-1')
AWS_SES_FROM_EMAIL = os.getenv('AWS_SES_FROM_EMAIL', 'noreply@yourdomain.com')
AWS_SES_CONFIGURATION_SET = os.getenv('AWS_SES_CONFIGURATION_SET', '')

# Password reset timeout (2 hours)
PASSWORD_RESET_TIMEOUT = 7200

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom apps
    'ai',
    'api',
    'applications',
    'config',
    'documents',
    'integrations',
    'ml_model',
    'ml_api',
    'notifications',
    'risk',
    'security',
    'users',
    'reports',
    
    # third party apps
    'rest_framework',
    'corsheaders',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'channels',
    'drf_spectacular',
    'drf_spectacular_sidecar',
]

# DRF Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'RiskGuard Pro API',
    'DESCRIPTION': 'Comprehensive Risk Assessment Platform API Documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'COMPONENT_SPLIT_REQUEST': True,
    'TAGS': API_TAGS,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'AUTHENTICATION_WHITELIST': [
        'users.authentication.CustomJWTAuthentication',
    ],
    'SERVERS': [
        {'url': 'https://api.riskguard.pro', 'description': 'Production server'},
        {'url': 'http://localhost:8000', 'description': 'Local development server'},
    ],
    'EXTENSIONS_INFO': {
        'x-logo': {
            'url': 'https://riskguard.pro/logo.png',
            'backgroundColor': '#FFFFFF',
            'altText': 'RiskGuard Pro Logo'
        }
    },
    'POSTPROCESSING_HOOKS': [
        'drf_spectacular.hooks.postprocess_schema_enums',
        'api.docs.hooks.custom_postprocessing_hook',
    ],
    # 'ENUM_NAME_OVERRIDES': {
    #     'users.enums.AuthStatus': 'AuthStatusEnum',
    # },
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'jwtAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Standard JWT Authentication'
            },
            'mfaAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'X-MFA-Token',
                'description': 'MFA Verification Token'
            }
        }
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'users.middleware.SessionTrackingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'security.middleware.BehavioralMiddleware',
    'security.middleware.PasswordExpirationMiddleware',
]

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',
    'x-timestamp',
    'x-request-timestamp',
    'cache-control',
    'x-processing-time-ms',
]

# For development only - remove in production
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CustomJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Channel Layers for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://localhost:6379/1')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
      'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'), 
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (profile pictures, uploads, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# ML Pipeline Configuration
ML_PROCESSING_ENABLED = os.getenv('ML_PROCESSING_ENABLED', 'True').lower() == 'true'
ML_AUTO_TRIGGER_ON_SUBMIT = os.getenv('ML_AUTO_TRIGGER_ON_SUBMIT', 'True').lower() == 'true'
ML_BATCH_SIZE = int(os.getenv('ML_BATCH_SIZE', '10'))
ML_RETRY_ATTEMPTS = int(os.getenv('ML_RETRY_ATTEMPTS', '3'))

# ML Model Configuration
ML_MODEL_PATH = os.path.join(BASE_DIR, 'ml_model', 'models')
ML_CONFIDENCE_THRESHOLD = float(os.getenv('ML_CONFIDENCE_THRESHOLD', '0.7'))
GHANA_EMPLOYMENT_ANALYSIS_ENABLED = os.getenv('GHANA_EMPLOYMENT_ANALYSIS_ENABLED', 'True').lower() == 'true'

# ===== Backblaze B2 Configuration (S3-Compatible Object Storage) =====
B2_APPLICATION_KEY_ID = os.getenv('B2_APPLICATION_KEY_ID', os.getenv('AWS_ACCESS_KEY_ID'))
B2_APPLICATION_KEY = os.getenv('B2_APPLICATION_KEY', os.getenv('AWS_SECRET_ACCESS_KEY'))
B2_BUCKET_NAME = os.getenv('B2_BUCKET_NAME', os.getenv('AWS_S3_BUCKET_NAME'))
B2_ENDPOINT_URL = os.getenv('B2_ENDPOINT_URL')  # e.g., https://s3.us-west-004.backblazeb2.com
B2_REGION = os.getenv('B2_REGION', 'us-east-1')

# ===== Resend Email Configuration =====
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', 'onboarding@resend.dev')

# ===== Document processing settings =====
DOCUMENT_PROCESSING_ENGINE = os.getenv('DOCUMENT_PROCESSING_ENGINE', 'tesseract')  # 'tesseract' or 'textract'
FALLBACK_TO_OCR_ON_TEXTRACT_FAILURE = os.getenv('FALLBACK_TO_OCR_ON_TEXTRACT_FAILURE', 'True').lower() == 'true'

# Ghana Card specific settings
GHANA_CARD_VALIDATION_ENABLED = True
GHANA_CARD_TEXTRACT_CONFIDENCE_THRESHOLD = float(os.getenv('GHANA_CARD_TEXTRACT_CONFIDENCE_THRESHOLD', '0.6'))
